version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # HTTP port
      - "6334:6334" # GRPC port (optional)
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  qdrant_data: {}